.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "skillastic monitor add" 1  "skillastic monitor add " 
.SH NAME
skillastic monitor add \- Register a project for monitoring (defaults to the current directory)
.SH SYNOPSIS
\fBskillastic monitor add\fR [\fB\-\-interval\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPATH\fR] 
.SH DESCRIPTION
Register a project for monitoring (defaults to the current directory)
.SH OPTIONS
.TP
\fB\-\-interval\fR \fI<INTERVAL>\fR [default: 300]
Poll interval in seconds
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATH\fR]

