.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "skillastic promoted" 1  "skillastic promoted " 
.SH NAME
skillastic promoted \- List and validate the promoted skill set
.SH SYNOPSIS
\fBskillastic promoted\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List and validate the promoted skill set
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
