.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "skillastic show" 1  "skillastic show " 
.SH NAME
skillastic show \- Show one skill in full
.SH SYNOPSIS
\fBskillastic show\fR [\fB\-\-docs\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Show one skill in full
.SH OPTIONS
.TP
\fB\-\-docs\fR
Render the human\-facing docs page instead of raw metadata
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Skill name
