.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "skillastic docs generate" 1  "skillastic docs generate " 
.SH NAME
skillastic docs generate \- Generate a docs page for a skill
.SH SYNOPSIS
\fBskillastic docs generate\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Generate a docs page for a skill
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Skill name
