.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "skillastic history" 1  "skillastic history " 
.SH NAME
skillastic history \- Show a skill\*(Aqs lineage chain and mutation history
.SH SYNOPSIS
\fBskillastic history\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Show a skill\*(Aqs lineage chain and mutation history
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Skill name
