.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "skillastic monitor resume" 1  "skillastic monitor resume " 
.SH NAME
skillastic monitor resume \- Start daemons for all enabled, not\-running projects
.SH SYNOPSIS
\fBskillastic monitor resume\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Start daemons for all enabled, not\-running projects
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
