.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "skillastic domain-model" 1  "skillastic domain-model " 
.SH NAME
skillastic domain\-model \- Generate or update the project\*(Aqs CONTEXT.md domain glossary
.SH SYNOPSIS
\fBskillastic domain\-model\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Generate or update the project\*(Aqs CONTEXT.md domain glossary
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
