.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "skillastic remove" 1  "skillastic remove " 
.SH NAME
skillastic remove \- Remove a skill
.SH SYNOPSIS
\fBskillastic remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Remove a skill
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Skill name
