.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "skillastic monitor list" 1  "skillastic monitor list " 
.SH NAME
skillastic monitor list \- Show all registered projects and whether their daemon is running
.SH SYNOPSIS
\fBskillastic monitor list\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show all registered projects and whether their daemon is running
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
