.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "skillastic doctor" 1  "skillastic doctor " 
.SH NAME
skillastic doctor \- Check workspace health and report actionable fixes
.SH SYNOPSIS
\fBskillastic doctor\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Check workspace health and report actionable fixes
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
