.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "skillastic adr" 1  "skillastic adr " 
.SH NAME
skillastic adr \- Create a new architectural decision record
.SH SYNOPSIS
\fBskillastic adr\fR [\fB\-h\fR|\fB\-\-help\fR] <\fITITLE\fR> 
.SH DESCRIPTION
Create a new architectural decision record
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fITITLE\fR>
Short title for the decision
