.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "skillastic events" 1  "skillastic events " 
.SH NAME
skillastic events \- Show recent daemon events recorded in the workspace state
.SH SYNOPSIS
\fBskillastic events\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show recent daemon events recorded in the workspace state
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
