.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "skillastic status" 1  "skillastic status " 
.SH NAME
skillastic status \- Version\-resolver report for all skills vs. the current app version
.SH SYNOPSIS
\fBskillastic status\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Version\-resolver report for all skills vs. the current app version
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
