.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH "skillastic verify" 1  "skillastic verify " 
.SH NAME
skillastic verify \- Mark a skill verified against the current app version
.SH SYNOPSIS
\fBskillastic verify\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Mark a skill verified against the current app version
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Skill name
